import React from 'react';
import {Outlet, Link} from "react-router-dom";

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class PathInfo {
    functionName: string;
    httpPath: string;
    httpMethod: string;

    constructor(functionName: string, httpPath: string, httpMethod: string) {
        this.functionName = functionName;
        this.httpPath = httpPath;
        this.httpMethod = httpMethod;
    }

    toString(): string {
        return "PathInfo["+this.functionName+","+this.httpPath+","+this.httpMethod+"]";
    }
}

class AuthRequest {}
class AuthResponse {}
class LoginRequest {}
class LoginResponse {}

const path: any = (thePath: string, type: any) => {
    return (target: Function, memberName: string, propertyDescriptor: PropertyDescriptor) => {
        const pathMeta = new PathInfo(memberName, path, type);

        Object.defineProperty(target, memberName+'pathInfo', {
            value: pathMeta,
            writable: false
        });

        //console.log("target="+target.pathInfo);
        console.log("member="+memberName);
        console.log("props="+propertyDescriptor);
    }
}

class AuthApiImpl {
    @path("/authenticate", AuthResponse)
    authenticate(request: AuthRequest): Promise<AuthResponse> {
        throw new Error("all this is generated by factory.createApiImpl");
    }
    @path("/login", LoginResponse)
    login(request: LoginRequest): Promise<LoginResponse> {
        throw new Error("all this is generated by factory.createApiImpl");
    }
};

export default function MainPage() {


    return (
    <div>
        <h1>Bookkeeper</h1>
        <nav
            style={{
                borderBottom: "solid 1px",
                paddingBottom: "1rem"
            }}
        >
            <Link to="/invoices">Invoices</Link> |{" "}
            <Link to="/expenses">Expenses</Link>
        </nav>
        <Outlet />
    </div>
);
}
